### ISSUE TITLE
App.test.js is failing. When data is fetched successfully > should not render loading text

### ISSUE THREAD

**Issue by ajunx8** [vaskort/custom-hook-test#1]
<img width="467" alt="Screenshot 2024-01-25 at 1 58 43 pm" src="https://github.com/vaskort/custom-hook-test/assets/106011081/1cea0c64-0b1b-4dac-98a0-1593081d46c6">

Do you have an explanation for why this happened?

I thought it could be because the test might be checking for the text too early. I tried different things like await waitFor() and act()... but the error still pops up.

Thanks

**Comment by vaskort** [comment]
Hi @ajunx8 thanks for raising this. The problem seems to be because the `cleanup` function from `react-testing-library` is not running automatically anymore as I have added this line here: https://github.com/vaskort/custom-hook-test/blob/develop/src/setupTests.js#L6

What you can do is to import the `cleanup` function from RTL and then run it on `beforeEach`, then your test would pass. 

You could debug this by running `screen.debug()` in your tests, you can see that the App is being rendered multiple times.

Also, would you like to contribute this change please? :)

**Comment by vaskort** [comment]
It should be fixed now!
